apiVersion: v1
kind: Pod
metadata:
  name: db01
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: dbdata
  volumes:
  - name: dbdata
    hostPath:
      path: /data 
      type: DirectoryOrCreate 
