apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
   app: vproapp
spec:
  containers:
  - name: appcontainer
    image: imranvisualpath/freshtomapp:V7
    ports:
      - containerPort: 8080
